name 'devops-challenge'
maintainer 'Leonardo Cardoso'
maintainer_email 'kibiluzbad@gmail.com'
license 'All rights reserved'
description 'Installs/Configures devops-challenge'
long_description 'Installs/Configures devops-challenge'
version '0.2.0'
source_url 'git@github.com:kibiluzbad/devops-challenge.git'
issues_url 'https://github.com/kibiluzbad/devops-challenge/issues'
chef_version '>= 12.5' if respond_to?(:chef_version)
supports 'centos'
depends 'java', '~> 1.50.0'
depends 'tomcat', '~> 3.0.0'